# Generated by Django 3.2.9 on 2022-01-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20220103_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='paint',
            field=models.ManyToManyField(to='main_app.Paint'),
        ),
    ]
